In [1]:
import tensorflow as tf

ModuleNotFoundError: No module named 'tensorflow'

In [2]:
pip install tensorflow -U

Note: you may need to restart the kernel to use updated packages.
Defaulting to user installation because normal site-packages is not writeable
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
     ---------------------------------------- 0.0/46.2 kB ? eta -:--:--
     ---------------------------------------- 46.2/46.2 kB 2.4 MB/s eta 0:00:00
   ---------------------------------------- 0.0/377.0 MB ? eta -:--:--
   ---------------------------------------- 0.2/377.0 MB 6.1 MB/s eta 0:01:02
   ---------------------------------------- 0.6/377.0 MB 7.9 MB/s eta 0:00:48
   ---------------------------------------- 1.2/377.0 MB 9.3 MB/s eta 0:00:41
   ---------------------------------------- 1.3/377.0 MB 8.9 MB/s eta 0:00:43
   ---------------------------------------- 2.2/377.0 MB 10.1 MB/s eta 0:00:38
   ---------------------------------------- 2.5/377.0 MB 10.1 MB/s eta 0:00:38
   ---------------------------------------- 3.4/377.0 MB 10.7

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [1]:
import tensorflow as tf

In [2]:
tf

<module 'tensorflow' from 'C:\\Users\\rajesh\\AppData\\Roaming\\Python\\Python311\\site-packages\\tensorflow\\__init__.py'>

##### Tensor

In [3]:
a = tf.constant([1,2,3])
b = tf.constant([4,5,6])

print("Tensor a:",a)
print("Tensor b:",b)

Tensor a: tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Tensor b: tf.Tensor([4 5 6], shape=(3,), dtype=int32)


In [4]:
a[0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [5]:
x = tf.constant([[1,2,3],[7,5,8]] )
y = tf.constant([[4,5],[9,0]])

print("Tensor a:",a)
print("Tensor b:",b)

Tensor a: tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Tensor b: tf.Tensor([4 5 6], shape=(3,), dtype=int32)


In [9]:
import numpy as np

In [10]:
np

<module 'numpy' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>

In [11]:
x = tf.constant([[1,2,3],[7,5,8]],dtype=np.int8)
y = tf.constant([[4,5],[9,0]])

print("Tensor x:",x)
print("Tensor y:",y)

Tensor x: tf.Tensor(
[[1 2 3]
 [7 5 8]], shape=(2, 3), dtype=int8)
Tensor y: tf.Tensor(
[[4 5]
 [9 0]], shape=(2, 2), dtype=int32)


In [12]:
x = tf.constant([[1,2,3],[7,5,8],[1,8,3],[7,4,8]],dtype=np.int8)
y = tf.constant([[4,5],[9,0]])

print("Tensor x:",x)
print("Tensor y:",y)

Tensor x: tf.Tensor(
[[1 2 3]
 [7 5 8]
 [1 8 3]
 [7 4 8]], shape=(4, 3), dtype=int8)
Tensor y: tf.Tensor(
[[4 5]
 [9 0]], shape=(2, 2), dtype=int32)


In [13]:
#add tensor

c=tf.add(a,b)
print("ADD: ",c)

ADD:  tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [14]:
a+b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 7, 9])>

In [15]:
a-b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-3, -3, -3])>

In [20]:
a.numpy()

array([1, 2, 3])

In [22]:
#Divide tensor

e=tf.divide(a,b)
print("Divide: ",e)

Divide:  tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)


In [23]:
#multilpy tensor

f=tf.multiply(a,b)
print("Multiply: ",f)

Multiply:  tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


In [25]:
#substract tensor

d=tf.subtract(a,b)
print("substract: ",d)

substract:  tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)


In [26]:
a/b

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.25, 0.4 , 0.5 ])>

In [27]:
b/a

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([4. , 2.5, 2. ])>

In [28]:
b//a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 2, 2])>

In [29]:
a//b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 0, 0])>

In [30]:
#matrix Multiplication
a_matrix = tf.constant([[4,1],[9,7]])

b_matrix = tf.constant([[4,5],[9,0]])

g=tf.matmul(a_matrix ,b_matrix)

print("Multiplication Of matrix x:",g)


Multiplication Of matrix x: tf.Tensor(
[[25 20]
 [99 45]], shape=(2, 2), dtype=int32)


In [33]:
tf.add

<function tensorflow.python.ops.math_ops.add(x, y, name=None)>