In [1]:
import cv2

In [2]:
import numpy as np

In [5]:
import matplotlib.pyplot as plt

In [7]:
image = cv2.imread("images/lenna.png")

height,width =image.shape[:2]

quarter_height ,quarter_width = height/4 ,width/4

T = np.float32([ [1,0,quarter_width] ,[0,1,quarter_height] ])

img_translation = cv2.warpAffine(image , T ,(width ,height))

In [8]:
T

array([[  1.,   0., 128.],
       [  0.,   1., 128.]], dtype=float32)

In [9]:
cv2.imshow("Original IMG", image)
cv2.imshow("Translated IMG",img_translation)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
T = np.float32([ [1,0,-40] ,[0,1,100 ] ])
img_translation = cv2.warpAffine(image , T ,(width ,height))
cv2.imshow("Original IMG", image)
cv2.imshow("Translated IMG",img_translation)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [12]:
T

array([[  1.,   0., -40.],
       [  0.,   1., 100.]], dtype=float32)

In [18]:
T = np.float32([ [1,0,-40] ,[0,1,100 ] ])
img_translation = cv2.warpAffine(image , T ,(width+100,height+100))

cv2.imshow("Original IMG", image)
cv2.imshow("Translated IMG",img_translation)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [16]:
T

array([[  1.,   0., -40.],
       [  0.,   1., 100.]], dtype=float32)