In [1]:
import numpy as np

##### Create the array

In [6]:
import numpy as np

In [7]:
 x = np.array([3,66,77,8,22,5])

In [8]:
print(x)

[ 3 66 77  8 22  5]


In [10]:
type(x)

numpy.ndarray

In [11]:
x.ndim

1

In [12]:
x

array([ 3, 66, 77,  8, 22,  5])

In [13]:
x.dtype

dtype('int32')

In [14]:
a = 3467134761783264568765924635689824357656

In [15]:
a

3467134761783264568765924635689824357656

In [19]:
a=345**345

In [20]:
a

352848113870204861357459895912531129403507172704013282541742157899456279557412465012695188583298962419493171929147862854772109625539123370910419162733970136188582502219077018174392588019423198314145997265220190235439566326342226152827240525807114608624322879668422640232363157410757905535424768044992698814421867109299929558304806683119893313844877531396486438431390305197452911262043462554411614485250599678028699591929429222180485479831487144383799325404119388131394426280664195692712093219933488338481596155234470038900215619397099277229999727378553536012752712026967888172763066075329584556914467936422537738938806778973045878665965306174689259116323832457431073476798297929944047699990387646687668142535928031312588786361817184205647774910846811845586215688015729558539113289643239674032170907304237918173615485980032335759315150792991833128553480491973459720611572265625

In [22]:
 x = np.array([3,66,77,8,22,5] , dtype=np.int8)

In [23]:
x

array([ 3, 66, 77,  8, 22,  5], dtype=int8)

In [24]:
x[0] = 127

In [25]:
x

array([127,  66,  77,   8,  22,   5], dtype=int8)

In [27]:
 x = np.array([3,66,77,8,22,5] , dtype=np.uint8)

In [28]:
x[0] = 127

In [29]:
x

array([127,  66,  77,   8,  22,   5], dtype=uint8)

In [32]:
x.size

6

In [33]:
x.shape

(6,)

In [34]:
x.min()

5

In [35]:
x.max()

244

In [36]:
x

array([244,  66,  77,   8,  22,   5], dtype=uint8)

In [38]:
x.mean()

70.33333333333333

In [39]:
x.resize()

In [40]:
x

array([244,  66,  77,   8,  22,   5], dtype=uint8)

In [41]:
 y = np.array([3,66,77.6,8,22,5])

In [43]:
type(y)

numpy.ndarray

In [45]:
y.dtype

dtype('float64')

In [50]:
 z = np.array([3,66,77.6,8,22,5,True])

In [51]:
z

array([ 3. , 66. , 77.6,  8. , 22. ,  5. ,  1. ])

In [52]:
type(z)

numpy.ndarray

In [53]:
z.dtype

dtype('float64')

In [54]:
z=np.zeros(10)

In [55]:
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [56]:
z=np.zeros(10,dtype = np.int16)

In [57]:
z

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [58]:
z=np.ones(10,dtype = np.int16)

In [59]:
z

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int16)

In [61]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [63]:
np.arange(2,20,4)

array([ 2,  6, 10, 14, 18])

In [64]:
np.arange(20,1,-4)

array([20, 16, 12,  8,  4])

In [66]:
np.arange(0,10,0.33)

array([0.  , 0.33, 0.66, 0.99, 1.32, 1.65, 1.98, 2.31, 2.64, 2.97, 3.3 ,
       3.63, 3.96, 4.29, 4.62, 4.95, 5.28, 5.61, 5.94, 6.27, 6.6 , 6.93,
       7.26, 7.59, 7.92, 8.25, 8.58, 8.91, 9.24, 9.57, 9.9 ])

In [67]:
np.arange(1,11,5)

array([1, 6])

##### Array Operations

In [69]:
n1 = np.array ([56,28,23,25,9])
n1 = np.array ([44,28,2,2,94])


In [70]:
n1 + 10

array([ 54,  38,  12,  12, 104])

In [71]:
n1 = np.array ([56,28,23,25,9])
n2 = np.array ([44,28,2,2,94])


In [72]:
n1 + 10

array([66, 38, 33, 35, 19])

In [73]:
n2 /5

array([ 8.8,  5.6,  0.4,  0.4, 18.8])

In [74]:
n1 * 2

array([112,  56,  46,  50,  18])

In [75]:
[56,28,23,25,9]*3

[56, 28, 23, 25, 9, 56, 28, 23, 25, 9, 56, 28, 23, 25, 9]

In [76]:
n1 + n2

array([100,  56,  25,  27, 103])

In [77]:
n1- n2

array([ 12,   0,  21,  23, -85])

In [78]:
n1*n2

array([2464,  784,   46,   50,  846])

In [79]:
n2 / n1

array([ 0.78571429,  1.        ,  0.08695652,  0.08      , 10.44444444])

##### MATRIX

In [81]:
M = np.array([ [2,3,4],[5,1,2],[7,8,9]])


M

In [84]:
M.dtype

dtype('int32')

In [85]:
M.size

9

In [87]:
M.ndim

2

In [88]:
M.shape

(3, 3)

In [89]:
M[2,1]

8

In [90]:
M[1:3][0:2]

array([[5, 1, 2],
       [7, 8, 9]])

In [91]:
M[1:2][0:1]

array([[5, 1, 2]])

In [92]:
M[1:2][0:2]

array([[5, 1, 2]])

In [93]:
M[0:2][0:1]

array([[2, 3, 4]])

In [94]:
M[0:1][1:3]

array([], shape=(0, 3), dtype=int32)

In [97]:
M1=M.reshape(3,3)

In [98]:
M1

array([[2, 3, 4],
       [5, 1, 2],
       [7, 8, 9]])

In [102]:
M.flatten()

array([2, 3, 4, 5, 1, 2, 7, 8, 9])

In [103]:
M.T

array([[2, 5, 7],
       [3, 1, 8],
       [4, 2, 9]])

In [104]:
M.min()

1

In [105]:
M.min(axis=1)

array([2, 1, 7])

In [106]:
M.min(axis=0)

array([2, 1, 2])

In [107]:
M.sum(axis=0)

array([14, 12, 15])

In [108]:
M.sum(axis=1)

array([ 9,  8, 24])

In [109]:
y

array([ 3. , 66. , 77.6,  8. , 22. ,  5. ,  0. ])

In [110]:
M.argmax()

8

In [111]:
M

array([[2, 3, 4],
       [5, 1, 2],
       [7, 8, 9]])

In [112]:
y

array([ 3. , 66. , 77.6,  8. , 22. ,  5. ,  0. ])

In [113]:
y.argmax()

2

In [114]:
M = M.astype(np.int16)

In [115]:
M

array([[2, 3, 4],
       [5, 1, 2],
       [7, 8, 9]], dtype=int16)

In [116]:
M = M.astype(np.float16)

In [117]:
M

array([[2., 3., 4.],
       [5., 1., 2.],
       [7., 8., 9.]], dtype=float16)

In [119]:
x

array([244,  66,  77,   8,  22,   5], dtype=uint8)

In [120]:
y=x

In [121]:
y

array([244,  66,  77,   8,  22,   5], dtype=uint8)

In [122]:
y[0]=20

In [123]:
y

array([20, 66, 77,  8, 22,  5], dtype=uint8)

In [124]:
x

array([20, 66, 77,  8, 22,  5], dtype=uint8)

In [125]:
id(y)

2349810950256

In [126]:
id(x)

2349810950256

In [127]:
x

array([20, 66, 77,  8, 22,  5], dtype=uint8)

In [128]:
y = x.copy

In [131]:
y = x.copy()

In [132]:
y[0]=28

In [133]:
y

array([28, 66, 77,  8, 22,  5], dtype=uint8)

In [134]:
x

array([20, 66, 77,  8, 22,  5], dtype=uint8)

In [135]:
id(x)

2349810950256

In [136]:
id(y)

2349835472880